/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp2;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        ProjectMenu.project();
    }
}